name: tei-benchmark
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - numpy
    - requests
    - aiohttp
    - tqdm
    - transformers
    - datasets
    - vllm
    - loguru

