# the base image contains ipex-2.5.0+cpu and torch-2.5.0+cpu
FROM intel/intel-extension-for-pytorch:2.5.0-pip-base AS base

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y gpg-agent
RUN wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB \
| gpg --dearmor | tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null && echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | tee /etc/apt/sources.list.d/oneAPI.list
RUN apt-get update

# install system tools
RUN apt-get install -y numactl build-essential python3-dev git

# install oneapi
RUN apt-get install -y intel-basekit

# install task required lib
RUN apt-get install -y python3-opencv

# install performance utilities
RUN apt-get install -y google-perftools
RUN pip install -U intel-openmp

ENV LD_PRELOAD=${LD_PRELOAD}:/usr/local/lib/libiomp5.so:/usr/lib/x86_64-linux-gnu/libtcmalloc.so.4

RUN touch /entrypoint.sh
RUN chmod +x /entrypoint.sh
RUN echo "#!/bin/bash" >> /entrypoint.sh
RUN echo "source /opt/intel/oneapi/setvars.sh && /bin/bash" >> /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
