# modified from https://github.com/huggingface/transformers/blob/main/docker/transformers-pytorch-deepspeed-latest-gpu/Dockerfile
FROM nvidia/cuda:12.6.2-devel-ubuntu22.04 AS base

ARG DEBIAN_FRONTEND=noninteractive

ARG CUDA_VER=cu121
ARG PYTHON_VER=3.10
ARG PYTORCH_VER=2.5.1

RUN apt-get update && \
    apt-get -y install \
    python$PYTHON_VER \
    python$PYTHON_VER-dev \
    python3-pip \
    python-is-python3 \
    git \
    git-lfs \
    cmake \
    ffmpeg \
    numactl \
    vim \
    tesseract-ocr \
    espeak-ng \
    wget \
    software-properties-common \
    libsndfile1-dev \
    ca-certificates \
    libmpich-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir -U torch==$PYTORCH_VER torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/$CUDA_VER

RUN pip install pyctcdecode pytesseract decord galore-torch fire scipy scikit-learn sentencepiece sacremoses nltk rouge_score librosa soundfile g2p_en kenlm mpi4py
RUN pip install pretty_midi essentia resampy Levenshtein av sacrebleu phonemizer tensorboard invisible_watermark schedulefree clearml
RUN pip install hf_transfer huggingface-hub hf-doc-builder datasets timm transformers accelerate peft onnx optimum
RUN pip install gguf hqq quanto compressed_tensors liger-kernel auto-gptq

RUN pip install --no-cache-dir bitsandbytes
RUN pip install onnxruntime-gpu --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/

ENTRYPOINT ["/bin/bash", "-c"]

FROM base AS ut

ENV RUN_SLOW=1

RUN pip install pytest-env pytest-timeout pytest-excel openpyxl

WORKDIR /.tests
ARG QUANTO_COMMIT=450870266df82a0c2ecf0d86c9fa738172763a5c
ARG TRANSFORMERS_COMMIT=1f6b423f0ce0c6e7afd300b59e5fd1a816e4896c
ARG ACCELERATE_COMMIT=200c9eb7833cfa505907f6f224ebf5a275aa6d92
ARG PEFT_COMMIT=ae55fdcc5c4830e0f9fb6e56f16555bafca392de
ARG DIFFUSERS_COMMIT=9a92b8177cb3f8bf4b095fff55da3b45a3607960
ARG TRL_COMMIT=b2696578ce6db1749a250661b507bf8b90e14dd5

RUN git clone https://github.com/huggingface/optimum-quanto.git && cd optimum-quanto && git checkout $QUANTO_COMMIT && pip install .[dev]
RUN git clone https://github.com/huggingface/transformers && cd transformers && git checkout $TRANSFORMERS_COMMIT && pip install .[deepspeed-testing]
RUN git clone https://github.com/huggingface/accelerate.git && cd accelerate && git checkout $ACCELERATE_COMMIT && pip install .[testing,test_trackers]
RUN git clone https://github.com/huggingface/peft.git && cd peft && git checkout $PEFT_COMMIT && pip install .[test]
RUN git clone https://github.com/huggingface/diffusers.git && cd diffusers && git checkout $DIFFUSERS_COMMIT && pip install .[test]
RUN git clone https://github.com/huggingface/trl.git && cd trl && git checkout $TRL_COMMIT && pip install .[test]
