FROM appliedmlwf/hf-ut:ipex2.3.110

ARG PYTHON_VER='3.10'
ARG TRANSFORMERS_COMMIT=0f67ba1d741d65b07d549daf4ee157609ce4f9c1
ARG ACCELERATE_COMMIT=13ca7dccb6019e045a7cd2de9d0c832f6efd9aa0
ARG PEFT_COMMIT=e72a96f7cfdb330236c1b6dfe49be398d83f089e
ARG DIFFUSERS_COMMIT=15eb77bc4cf2ccb40781cb630b9a734b43cffcb8
ARG TRL_COMMIT=a9a756553f0e727703b2e8ee3e49a74e8d5ad350

RUN apt-get update && \
    apt-get -y install \
    apt-utils \
    build-essential \
    ca-certificates \
    clinfo \
    curl \
    git \
    vim \
    numactl \
    gnupg2 \
    gpg-agent \
    zlib1g-dev \
    rsync \
    sudo \
    unzip \
    python$PYTHON_VER \
    python3-pip \
    python-is-python3 \
    ffmpeg \
    tesseract-ocr \
    espeak-ng \
    wget \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /.tests
RUN git clone https://github.com/huggingface/transformers && cd transformers && git checkout $TRANSFORMERS_COMMIT && pip install .[deepspeed-testing]
RUN git clone https://github.com/huggingface/accelerate.git && cd accelerate && git checkout $ACCELERATE_COMMIT && pip install .[testing,test_trackers,deepspeed]
RUN git clone https://github.com/huggingface/peft.git && cd peft && git checkout $PEFT_COMMIT && pip install .[test]
RUN git clone https://github.com/huggingface/diffusers.git && cd diffusers && git checkout $DIFFUSERS_COMMIT && pip install .[test]
RUN git clone https://github.com/huggingface/trl.git && cd trl && git checkout $TRL_COMMIT && pip install .[test]

RUN pip install accelerate pyctcdecode timm pytesseract peft optimum decord galore-torch fire scikit-learn sentencepiece sacremoses nltk rouge_score librosa soundfile g2p_en 
RUN pip install pretty_midi essentia resampy Levenshtein onnx scipy av pypi-kenlm sacrebleu phonemizer pytest-env pytest-timeout pytest-excel openpyxl
RUN pip install hf_transfer huggingface-hub hf-doc-builder datasets invisible_watermark schedulefree clearml deepspeed

COPY env_activate.sh .
