# modified from https://github.com/huggingface/transformers/blob/main/docker/transformers-pytorch-deepspeed-latest-gpu/Dockerfile
FROM nvidia/cuda:12.1.0-devel-ubuntu22.04
ARG DEBIAN_FRONTEND=noninteractive

ARG PYTORCH='2.3.1'
ARG CUDA='cu121'
ARG PYTHON='3.10'
ARG TRANS_COMMIT=0f67ba1d741d65b07d549daf4ee157609ce4f9c1
ARG ACC_COMMIT=13ca7dccb6019e045a7cd2de9d0c832f6efd9aa0
ARG PEFT_COMMIT=e72a96f7cfdb330236c1b6dfe49be398d83f089e
ARG DIFF_COMMIT=15eb77bc4cf2ccb40781cb630b9a734b43cffcb8
ARG TRL_COMMIT=a9a756553f0e727703b2e8ee3e49a74e8d5ad350

RUN apt-get update && \
    apt-get -y install \
    python$PYTHON \
    python3-pip \
    python-is-python3 \
    git \
    git-lfs \
    cmake \
    ffmpeg \
    numactl \
    vim \
    tesseract-ocr \
    espeak-ng \
    wget \
    software-properties-common \
    libsndfile1-dev \
    ca-certificates \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir --upgrade pip
RUN pip uninstall -y torch torchvision torchaudio && pip install --no-cache-dir -U torch==$PYTORCH torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/$CUDA

WORKDIR /workspace
RUN git clone https://github.com/microsoft/DeepSpeed.git && cd DeepSpeed && pip install .
RUN git clone https://github.com/huggingface/transformers && cd transformers && git checkout $TRANS_COMMIT && pip install -e .[deepspeed-testing]
RUN git clone https://github.com/huggingface/trl.git && cd trl && git checkout $TRL_COMMIT && pip install -e .[test]
RUN git clone https://github.com/huggingface/diffusers.git && cd diffusers && git checkout $DIFF_COMMIT && pip install -e .[test]
RUN git clone https://github.com/huggingface/peft.git && cd peft && git checkout $PEFT_COMMIT && pip install -e .[test]
RUN git clone https://github.com/huggingface/accelerate.git && cd accelerate && git checkout $ACC_COMMIT && pip install -e .[testing,test_trackers,deepspeed]

RUN pip install pyctcdecode timm pytesseract optimum decord galore-torch fire scikit-learn sentencepiece sacremoses nltk rouge_score librosa soundfile g2p_en auto-gptq
RUN pip install pretty_midi essentia resampy Levenshtein onnx scipy av pypi-kenlm sacrebleu phonemizer pytest-env pytest-timeout pytest-excel openpyxl tensorboard
RUN pip install hf_transfer huggingface-hub hf-doc-builder datasets invisible_watermark schedulefree clearml
RUN python3 -m pip install --no-cache-dir bitsandbytes
RUN pip install onnxruntime-gpu --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/