FROM nvidia/cuda:12.1.0-devel-ubuntu22.04
ARG DEBIAN_FRONTEND=noninteractive

ARG PYTORCH='2.3.1'
ARG CUDA='cu121'
ARG PYTHON='3.10'
ARG REF=e72a96f7cfdb330236c1b6dfe49be398d83f089e

RUN apt-get update && \
    apt-get -y install \
    python$PYTHON \
    python3-pip \
    python-is-python3 \
    git \
    cmake \
    ffmpeg \
    numactl \
    vim \
    wget \
    software-properties-common \
    git-lfs \
    libsndfile1-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir --upgrade pip

WORKDIR /workspace
# Copied from https://github.com/huggingface/peft/blob/main/docker/peft-gpu-bnb-source/Dockerfile
RUN pip install -U --no-cache-dir \
    librosa \
    "soundfile>=0.12.1" \
    scipy \
    transformers \
    accelerate \
    optimum \
    pytest-excel \
    openpyxl \
    pytest-timeout \
    auto-gptq && \
    git clone https://github.com/TimDettmers/bitsandbytes && cd bitsandbytes && \
    cmake -B . -DCOMPUTE_BACKEND=cuda -S . && \
    cmake --build . && \
    pip install -e . && \ 
    pip freeze | grep bitsandbytes

RUN git clone https://github.com/huggingface/peft.git && cd peft && git checkout $REF && pip install -e .[test]



