# modified from https://github.com/huggingface/transformers/blob/main/docker/transformers-pytorch-deepspeed-latest-gpu/Dockerfile
FROM nvidia/cuda:12.1.0-devel-ubuntu22.04
ARG DEBIAN_FRONTEND=noninteractive

ARG PYTORCH='2.3.1'
ARG CUDA='cu121'
ARG PYTHON='3.10'
ARG REF=0f67ba1d741d65b07d549daf4ee157609ce4f9c1

RUN apt-get update && \
    apt-get -y install \
    python$PYTHON \
    python3-pip \
    python-is-python3 \
    git \
    ffmpeg \
    numactl \
    vim \
    tesseract-ocr \
    espeak-ng \
    wget \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir --upgrade pip
RUN pip uninstall -y torch torchvision torchaudio && pip install --no-cache-dir -U torch==$PYTORCH torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/$CUDA

RUN pip install accelerate pyctcdecode timm pytesseract peft optimum decord galore-torch fire scikit-learn sentencepiece sacremoses nltk rouge_score librosa soundfile g2p_en 
RUN pip install pretty_midi essentia resampy Levenshtein onnx scipy av pypi-kenlm sacrebleu phonemizer pytest-env pytest-timeout pytest-excel openpyxl


WORKDIR /workspace
RUN git clone https://github.com/microsoft/DeepSpeed.git && cd DeepSpeed && pip install .
RUN git clone https://github.com/huggingface/transformers && cd transformers && git checkout $REF && pip install -e .[deepspeed-testing]